temp="hello world"  
print(temp)
temp1=50
print(temp1)
temp2=60.5
print(temp2)
temp3=5j
print(temp3)
temp4=["tit","for","tat"]
print(temp4)
temp5=("tit","for","tat")
print(temp5)
temp6=range(10)
print(temp6)
temp7={"name:":"keerthana","age":20}
print(temp7)
temp8=True
print(temp8)
temp9=b"python"
print(temp9)
temp10=bytearray(4)
print(temp10)
